version: '3'
services:
  postgresql_kong:
    image: docker.io/bitnami/postgresql:11
    volumes:
      - postgresql_kong_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=kong
      - POSTGRESQL_PASSWORD=bitnami
      - POSTGRESQL_DATABASE=kong
    networks:
      - dataops_net
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 512M
  kong:
    image: docker.io/bitnami/kong:2
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
    environment:
      - KONG_MIGRATE=yes
      - KONG_PG_HOST=postgresql_kong
      - KONG_PG_PASSWORD=bitnami
      - KONG_ADMIN_HTTP_PORT_NUMBER=8001
      - KONG_ADMIN_LISTEN_ADDRESS=0.0.0.0
    hostname: kong
    networks:
      - dataops_net
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 512M

volumes:
  postgresql_kong_data:
    driver: local

networks:
  dataops_net:
    external:
      name: dataops_net
